changes to cmake files for compiling with chibios v17 chstream changed to hal_stream, functions renamed accordingly osThreadDef adds an extra 'name' parameter TODO: undefined reference to `sduDisconnectI' and `asm' during build